server:
  port:
    8080
spring:
#  profiles:
#    active: ${PROFILE:local}
#  banner:
#    location: classpath:/banner.txt
  application:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    java: "@java.version@"
ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost
    port: 1414
    user: admin
    password: passw0rd
    queueRequest: DEV.QUEUE.1
    queueResponse: DEV.QUEUE.1